### ISSUE TITLE
MediaType

### ISSUE THREAD

**Issue by hofmannv** [ISE-FIZKarlsruhe/nfdicore#28]
Somehow i can't re-open #15, but i think the issue is not solved. 

There could be some benefit for the Core-Ontology to think the Media-Type and Media-Format on a more general scale than on the level of "Media". Please see my [comment](https://github.com/ISE-FIZKarlsruhe/nfdicore/issues/15#issuecomment-1429481591) in #15

**Comment by joergwa** [comment]
reopened 15
