### ISSUE TITLE
Resource class

### ISSUE THREAD

**Issue by aazocar** [ISE-FIZKarlsruhe/nfdicore#34]
The Resource class is defined as the subclass of the union of `schema:CreativeWork or schema:Intangible or schema:Product`. And most of the properties have Resource in the domain or range. 

If, for example, one has 'article1' as an instance of a Publication and not of Resource, it will have no properties associated to it. So, every instance should go both under Publication and Resource. (This is true for all subclasses of the schema classes) 

- Is there a reason why Resource is the subclass of the union of the schema classes and not equivalent? If the Resource class is equivalent to the union, it means that the 'article1' instance of a Publication does not need to be explicitly added as an instance of Resource, but it can be inferred. And, there will not be the possibility of having an instance with no properties associated to it. Conceptually, I think all classes under CreativeWork, Intangible or Product are also Resources.

- Another scenario would be to have the subclasses which are right now under schema classes (Publication, Dataset, Software, Collection, Specification, Service, Website) as subclasses of the Resource class. Right now, in version 1.1.0, some of these classes (Software, Collection and Website) were changed from schema:Product to nfdicore:Resource. If all the classes are under Resource, it also solves the issue mentioned above. However, there would be no need for the schema classes in that case. 

I would like to know what everyone thinks about this. 

Also, @saidfathalla and @hofmannv please add further info if the description of the issue is not so clear 😄

**Comment by joergwa** [comment]
Thank you for raising this discussion. It makes sense for me too. The second solution does not require inferencing. 

@SashaVsesviatska what do you think? Does this affect the culture KG?

**Comment by joergwa** [comment]
After internal discussion we prefer the second solution, but we prefer to keep the schema classes.

**Comment by aazocar** [comment]
Thanks for updating this!
