### ISSUE TITLE
Proposal: Adaption of service classes in comparison to the requirements of the DFG Data Sheet/White Paper NFDI Taskforce Evaluation und Reporting

### ISSUE THREAD

**Issue by lsoehn** [ISE-FIZKarlsruhe/nfdicore#54]
NFDIcore defines the following classes as subclasses of nfdicore:Service:

consulting & funding, information & documentation, learning & teaching, linkage & enrichment, participation & collaboration, publication & dissemination, storage & preservation

My suggestion would be to change these service types compared to those of the NFDI Task Force on Evaluation and Reporting (see https://doi.org/10.5281/zenodo.10101412 ), which are relevant for evaluations of the NFDI consortia with regard to the DFG data sheet (see https://www.dfg.de/en/research-funding/funding-initiative/nfdi/guide-to-filling-out-the-supplementary-data-sheet-for-consortia-of-the-national-research-data-infrastructure-nfdi- ) or to take them in another way into account. I think, this could be useful in the context of the wider NFDI.

The Service Types following the White Paper are:

1. Databases
2. Libraries/APIs
3. Workflows/Pipelines
4. Tools/Applications
5. Web applications
6. Support/Consulting
7. Data Curation
8. Training
9. Storage

Definitions can be found there as well. What do you think?

**Comment by joergwa** [comment]
Thank you! Your suggestions will be considered int he next release.
