### ISSUE TITLE
Definition of nfdicore:contactPoint

### ISSUE THREAD

**Issue by lsoehn** [ISE-FIZKarlsruhe/nfdicore#55]
The definition of nfdicore:contactPoint is "The property is a relationship between a resource and a contact point." Domain of nfdicore:contactPoint is nfdicore:project or nfdicore:resource. Range is nfdicore:Agent. Therefore, I think the definition should be updated in a similar way as the one of nfdicore:contributor. 

Proposal: "The property relates a resource or a project to a person or an organization that serves as contact point for it."

**Comment by joergwa** [comment]
Thank you for this suggestion! We will add it to the upcoming version.
